SCHEMAS = {
    "auxiliary": {
        "Time": "object",
        "Unnamed: 1": "float64",
        "CanSigActTorq": "int64",
        "DCBusCurr": "int64",
        "DiIn1": "int64",
        "DiIn2": "int64",
        "DiIn3": "int64",
        "DiIn4": "int64",
        "DiIn5": "int64",
        "DiIn6": "int64",
        "DiIn7": "int64",
        "DiIn8": "int64",
        "DiIn9": "int64",
        "EncIn2A": "int64",
        "EncIn2B": "int64",
        "DiIn13": "int64",
        "EncIn1C": "int64",
        "EncIn1A": "int64",
        "EncIn1B": "int64",
        "AbiAccCurr": "int64",
        "IdArms": "int64",
        "IqArms": "int64",
        "UdRef": "int64",
        "UqRef": "int64",
        "ActLimType": "int64",
        "RegStat": "int64",
        "SensAng": "int64",
        "Iq": "int64",
        "Id": "int64",
        "ReaToSWOn": "int64",
        "SwOn": "int64",
        "Ena": "int64",
        "Trip": "float64",
        "CurrAbiRed": "float64",
        "CurrBoosAct": "float64",
        "ErrAct": "float64",
        "WarnAct": "float64",
        "Regen": "float64",
        "ODOut1On": "float64",
        "ODOut2On": "float64",
        "ODOut3On": "float64",
        "ODOut4On": "float64",
        "ODOut5On": "float64",
        "ODOut6On": "float64",
        "CanSigRotSpeedInRPM": "float64",
        "CanSigRmsMotCurr": "float64",
        "FiltVolt": "float64",
        "Event1": "float64",
        "Event2": "float64",
        "Event3": "float64",
        "Event4": "float64",
        "MotTemp": "float64",
        "HeatSTemp": "float64",
        "ActContMode": "float64",
        "ActEvent": "float64",
        "DCBusPow": "float64",
        "UpeakNorm": "float64",
        "VoltAng": "float64",
        "RefTorq": "float64"
    },

    "auxiliary_input": {
        "Time": "int",
        "Unnamed: 1": "int",
        "CommTorq": "int",
        " CommAcCurr": "int",
        " CommVolt": "int",
        " CommControlMode": "int",
        " CommSwitchOn. CommSpdNeutBrakeRampParSet": "int",
        " CommEnable": "float",
        " CommRegulSet": "int",
        " CommActCurrBoost": "int",
        " CommSpeedRampParSet": "int",
        " CommIgnore": "int",
        "LowDCBus": "int",
        " CommHighSideSwitchOn": "int",
        " CommOpenDrain1On": "int",
        " CommOpenDrain2On": "int",
        " CommOpenDrain3On": "float",
        " CommOpenDrain4On": "int",
        " CommOpenDrain5On": "float",
        " CommOpenDrain6On": "float",
        " CommSpeed": "float",
        " CommAccChang": "int",
        " CommDecelChange": "int",
        " AccTorqLimit": "int",
        " BrakeTorqLimit": "int",
        " PosDcCurrLimit": "int",
        " NegDcCurrLimit": "float"
    },
    "battery1": {
        "Time": "int",
        "Unnamed: 1": "int",
        "ISOQui": "int",
        "HWConfFau": "int",
        "MSDOpen": "int",
        "DaiCommErr": "int",
        "DaiCommWarn": "int",
        "HVILExADC": "int",
        "HVILInErr": "int",
        "HVILInADC": "int",
        "ISOADC": "int",
        "BDUOPWarn": "int",
        "BDUOPErr": "int",
        "InPresVld": "int",
        "OutPresVld": "int",
        "CellBalErr": "int",
        "Aux5VVld": "int",
        "EnThr": "int",
        "DisEnThr": "int",
        "MaxChrPwr": "float",
        "MaxDisPwr": "float",
        "CellVMin": "float",
        "CellVMax": "float",
        "CoolReq": "int",
        "HeatReq": "int",
        "ISOResNeg": "int",
        "ISOResPos": "int",
        "SOC": "float",
        "SOH": "int",
        "EnRema": "float",
        "CellSOCMin": "float",
        "CellSOCMax": "float",
        "TempAvg": "int",
        "TempMax": "int",
        "TempMin": "int",
        "InPres": "float",
        "OutPres": "float",
        "BDUTemp": "int",
        "BDUHum": "int",
        "ChrTime": "int",
        "DisTime": "int",
        "FullCharCou": "int",
        "OpTime": "int",
        "RemChrTime": "int",
        "MaxChrCurr": "float",
        "MaxDisCurr": "float",
        "MaxChrPwrChrgr": "float",
        "MaxChrCurrChrgr": "float",
        "LinkVol": "float",
        "PackCurr": "float",
        "PackVol": "float",
        "BattSts": "int",
        "NegRly": "int",
        "PosRly": "int",
        "PreRly": "int",
        "EndChrSts": "int",
        "ISOAct": "int",
        "CAN1": "int",
        "CAN3": "int",
        "LED": "int",
        "PackID": "int",
        "MaxPackSta": "int",
        "CAN3Baud": "int",
        "Heartb": "int",
        "ConnPackSta": "int",
        "AccelHi": "int",
        "CellBal": "int",
        "MsgLossConf": "int",
        "HWVer": "int",
        "SWVer": "int"
    },
    "battery1_input": {
        "Time": "object",
        "Unnamed: 1": "float",
        "AmbiTemp": "int",
        " SetChrgSocLim": "int",
        " SetChrgVltLim": "int",
        " SleepCmd": "int",
        " NormPowUpCmd": "int",
        " NormPowDownCmd": "int",
        " EmergPowDownCmd": "int",
        " PlugInChrgCmd": "int",
        " EndOfChargeCmd": "int",
        " ISODisCmd": "int",
        " DisLEDCmd": "int",
        " SetDisLedCmd": "int",
        " SelPackID": "int",
        " SetPackId": "int",
        " SelMaxPackInStack": "int",
        " SetMaxPackInStack": "int",
        " ConKey": "int",
        " CrashSts": "int",
        " ServiceMode": "float",
        " SetServiceModeCmd": "float"
    },
    "chargecontroller1": {
        "Time": "object",
        "Unnamed: 1": "float",
        "PP": "int",
        "CP": "int",
        "ACCharPoss": "int",
        "CPDuty": "int",
        "InlACTemp": "float",
        "InlDCTemp": "float",
        "HVSWTemp": "float",
        "HVPlugTemp": "float",
        "AuxTemp": "float",
        "EVSEID": "int",
        "PresCurr": "float",
        "PresVolt": "float",
        "CRC": "int",
        "SeqCount": "int",
        "HVSW1StateReq": "int",
        "HVSW2StateReq": "int",
        "PlugState": "int",
        "IL1State": "int",
        "IL2State": "int",
        "EmergShut": "int",
        "HWVers": "int",
        "CANVers": "int",
        "SWMajVers": "int",
        "SWBuildVers": "int",
        "SWMinVers": "int",
        "MinCurrLim": "float",
        "MinVoltLim": "float",
        "EnerToBeDeli": "int",
        "PeakCurrRipp": "float",
        "CurrRegTol": "float",
        "EVSEState": "int",
        "PowLimAch": "int",
        "CurrLimAch": "int",
        "VoltLimAch": "int",
        "WakeUpReas": "int",
        "LockState": "int",
        "HVSWState": "int",
        "CCLState": "int",
        "TargCurr": "float",
        "ChargMode": "int",
        "DTC_AWL": "int",
        "DTC_PL": "int",
        "DTC_RSL": "int",
        "ActChargProt": "int",
        "MaxCurrLim": "float",
        "MaxVoltLim": "float",
        "MaxPowLim": "int",
        "ErrorNo": "int",
        "EVSEStatCode": "int",
        "ButtonState": "int",
        "ShutDownReq": "int"
    },
    "CCL1": {
        "Time": "object",
        "Unnamed: 1": "float64",
        "PP": "int64",
        "CP": "int64",
        "ACCharPoss": "int64",
        "CPDuty": "int64",
        "InlACTemp": "float64",
        "InlDCTemp": "float64",
        "HVSWTemp": "float64",
        "HVPlugTemp": "float64",
        "AuxTemp": "float64",
        "EVSEID": "int64",
        "PresCurr": "float64",
        "PresVolt": "float64",
        "CRC": "int64",
        "SeqCount": "int64",
        "HVSW1StateReq": "int64",
        "HVSW2StateReq": "int64",
        "PlugState": "int64",
        "IL1State": "int64",
        "IL2State": "int64",
        "EmergShut": "int64",
        "HWVers": "int64",
        "CANVers": "int64",
        "SWMajVers": "int64",
        "SWBuildVers": "int64",
        "SWMinVers": "int64",
        "MinCurrLim": "float64",
        "MinVoltLim": "float64",
        "EnerToBeDeli": "int64",
        "PeakCurrRipp": "float64",
        "CurrRegTol": "float64",
        "EVSEState": "int64",
        "PowLimAch": "int64",
        "CurrLimAch": "int64",
        "VoltLimAch": "int64",
        "WakeUpReas": "int64",
        "LockState": "int64",
        "HVSWState": "int64",
        "CCLState": "int64",
        "TargCurr": "float64",
        "ChargMode": "int64",
        "DTC_AWL": "int64",
        "DTC_PL": "int64",
        "DTC_RSL": "int64",
        "ActChargProt": "int64",
        "MaxCurrLim": "float64",
        "MaxVoltLim": "float64",
        "MaxPowLim": "int64",
        "ErrorNo": "int64",
        "EVSEStatCode": "int64",
        "ButtonState": "int64",
        "ShutDownReq": "int64"
    },

    "CCL1_input": {
        "Time": "object",
        "Unnamed: 1": "float",
        "EVCCID": "int",
        " LED1PWM": "float",
        " LED2PWM": "float",
        " LED3PWM": "float",
        " LED4PWM": "float",
        " CRC": "int",
        " SeqCounter": "int",
        " HVSW1State": "int",
        " HVSW2State": "int",
        " VehVolt": "float",
        " InletVolt": "float",
        " EmergSep": "int",
        " EVRemainTimeToBulkSOC": "int",
        " EVCabinCond": "int",
        " EVRessCond": "int",
        " EVBulkSOC": "float",
        " EVRemTimeToFullSOC": "int",
        " EVBulkChargComp": "float",
        " EVFullSOC": "float",
        " EVTargCurr": "float",
        " EVTargVolt": "float",
        " EVSOC": "int",
        " EVError": "int",
        " EVEnergReq": "float",
        " EVDCMaxCurrLimit": "int",
        " EVDCMaxPowLimit": "float",
        " EVDCMaxVoltLimit": "int",
        " LockPerm": "int",
        " UnlockPerm": "int",
        " HVReady": "int",
        " ChargPerm": "int",
        " RestartChargCyc": "int",
        " PauseReq": "int",
        " Reneg": "int"
    },
    "chiller1": {
        "Time": "object",
        "Unnamed: 1": "float64",
        "HypStat": "int64",
        "HypTimeOut": "int64",
        "DCDCStat": "int64",
        "DCDCTimeOut": "int64",
        "WPIntStat": "int64",
        "WPIntTimeOut": "int64",
        "WPExtStat": "int64",
        "WPExtTimeOut": "int64",
        "HVHStat": "int64",
        "HVHTimeOut": "int64",
        "FAN1Stat": "int64",
        "FAN1TimeOut": "int64",
        "FAN2Stat": "int64",
        "FAN2TimeOut": "int64",
        "HVUndVolt": "int64",
        "HVOverVolt": "int64",
        "LVUndVolt": "int64",
        "LVOverVolt": "int64",
        "VDD12UndVolt": "int64",
        "VDD12OverVolt": "int64",
        "CoolLevStat": "int64",
        "STCSensStat": "int64",
        "ECUErr": "int64",
        "STM": "int64",
        "DetConfig": "int64",
        "CoolAvail": "int64",
        "HeatAvail": "int64",
        "DetCANProt": "int64",
        "Fan1Speed": "int64",
        "Fan2Speed": "int64",
        "PumpExtSpeed": "int64",
        "PumpIntSpeed": "int64",
        "CoolTemp": "int64",
        "PowConsHVH": "int64",
        "PowConsHyper": "int64",
        "PowLimCalc": "int64",
        "SLIInpPwr": "float64",
        "HV": "float64",
        "Cmpr": "int64",
        "Rel": "float64",
        "HeatrSts": "int64",
        "HVILSts": "int64",
        "Mode": "int64",
        "CooltLvl": "int64"
    },


    "chiller1_input": {
        "Time": "object",
        "Unnamed: 1": "float",
        " ThermSysStrt": "int",
        " PackNameThem": "int",
        " EnaCoolgHeatBat": "int",
        " TAct": "float",
        " TSetPoint": "float"
    },

    "DCDC": {
        "Time": "float",  # Column is all NaN in df.info()
        "Unnamed: 1": "int",
        "CurrOut": "int",
        "VoltOut": "int",
        "Temp": "int",
        "Enabled": "int",
        "VoltSetpoint": "int",
        "InputCurr": "int",
        "InputVolt": "int"
    },
    "drive1": {
        "Time": "object",
        "Unnamed: 1": "float",
        "ModATemp": "float",
        "ModBTemp": "float",
        "ModCTemp": "float",
        "GateDriTemp": "float",
        "ContTemp": "float",
        "RTD1Temp": "float",
        "RTD2Temp": "float",
        "StallBurTemp": "float",
        "CoolTemp": "float",
        "HotSpotTemp": "float",
        "MotTemp": "float",
        "TorqShud": "float",
        "OilTemp": "float",
        "OilPres": "float",
        "AnIn4": "float",
        "AnIn5": "float",
        "AnIn6": "float",
        "DiIn1": "int",
        "DiIn2": "int",
        "DiIn3": "int",
        "DiIn4": "int",
        "DiIn5": "int",
        "DiIn6": "int",
        "DiIn7": "int",
        "DiIn8": "int",
        "MotAngElec": "float",
        "MotRPM": "int",
        "ElecOutFreq": "float",
        "DeltResFilt": "float",
        "PhaATemp": "float",
        "PhaBTemp": "float",
        "PhaCTemp": "float",
        "DCCurr": "float",
        "DCVolt": "float",
        "OutVolt": "float",
        "VABVd": "float",
        "VBCVq": "float",
        "Vdff": "float",
        "Vqff": "float",
        "Id": "float",
        "Iq": "float",
        "Ref15": "float",
        "Ref25": "float",
        "Ref50": "float",
        "Ref120": "float",
        "VSM": "int",
        "PWM": "int",
        "InvSta": "int",
        "R1": "int",
        "R2": "int",
        "R3": "int",
        "R4": "int",
        "R5": "int",
        "R6": "int",
        "Run": "int",
        "SelfSens": "int",
        "DisSta": "int",
        "CommMode": "int",
        "RollCoun": "int",
        "EnaSta": "int",
        "BurstMod": "int",
        "KeySta": "int",
        "EnaLock": "int",
        "DirComm": "int",
        "BMSAct": "int",
        "BMSTLim": "int",
        "LimMaxRPM": "int",
        "LimHotSpot": "int",
        "LowRPMLim": "int",
        "LimCoolDer": "int",
        "LimStallBur": "int",
        "PostLo": "int",
        "PostHi": "int",
        "RunLo": "int",
        "RunHi": "int",
        "CommTorq": "float",
        "TorqFeed": "float",
        "PowOnTime": "float",
        "ModInd": "float",
        "FluxWeakOut": "float",
        "IdComm": "float",
        "IqComm": "float",
        "ProjCode": "int",
        "SWVer": "int",
        "MMDD": "int",
        "YYYY": "int",
        "DiagRec": "int",
        "DiagSeg": "int",
        "DiagGRes": "float",
        "DiagGObs": "float",
        "DiagSin": "int",
        "FTorqComm": "float",
        "FTorqFeed": "float",
        "FMotRPM": "int",
        "FDCVolt": "float",
        "ParRespAdd": "int",
        "ParRespWri": "int",
        "ParRespDat": "int"
    },

    "drive1_input": {
        "Time": "object",
        "Unnamed: 1": "float",
        "TorqueComm": "float",
        " SpeedComm": "int",
        " DirectComm": "int",
        " InvEnable": "int",
        " InvDischarge": "int",
        " SpeedModeOn": "int",
        " RollingCount": "int",
        " TorqueLimitComm": "float",
        " ParaAdd": "int",
        " ParaRWComm": "int",
        " ParaData": "int"
    },

    "drive2": {
        "Time": "object",
        "Unnamed: 1": "float",
        "ModATemp": "float",
        "ModBTemp": "float",
        "ModCTemp": "float",
        "GateDriTemp": "float",
        "ContTemp": "float",
        "RTD1Temp": "float",
        "RTD2Temp": "float",
        "StallBurTemp": "float",
        "CoolTemp": "float",
        "HotSpotTemp": "float",
        "MotTemp": "float",
        "TorqShud": "float",
        "OilTemp": "float",
        "OilPres": "float",
        "AnIn4": "float",
        "AnIn5": "float",
        "AnIn6": "float",
        "DiIn1": "int",
        "DiIn2": "int",
        "DiIn3": "int",
        "DiIn4": "int",
        "DiIn5": "int",
        "DiIn6": "int",
        "DiIn7": "int",
        "DiIn8": "int",
        "MotAngElec": "float",
        "MotRPM": "int",
        "ElecOutFreq": "float",
        "DeltResFilt": "float",
        "PhaATemp": "float",
        "PhaBTemp": "float",
        "PhaCTemp": "float",
        "DCCurr": "float",
        "DCVolt": "float",
        "OutVolt": "float",
        "VABVd": "float",
        "VBCVq": "float",
        "Vdff": "float",
        "Vqff": "float",
        "Id": "float",
        "Iq": "float",
        "Ref15": "float",
        "Ref25": "float",
        "Ref50": "float",
        "Ref120": "float",
        "VSM": "int",
        "PWM": "int",
        "InvSta": "int",
        "R1": "int",
        "R2": "int",
        "R3": "int",
        "R4": "int",
        "R5": "int",
        "R6": "int",
        "Run": "int",
        "SelfSens": "int",
        "DisSta": "int",
        "CommMode": "int",
        "RollCoun": "int",
        "EnaSta": "int",
        "BurstMod": "int",
        "KeySta": "int",
        "EnaLock": "int",
        "DirComm": "int",
        "BMSAct": "int",
        "BMSTLim": "int",
        "LimMaxRPM": "int",
        "LimHotSpot": "int",
        "LowRPMLim": "int",
        "LimCoolDer": "int",
        "LimStallBur": "int",
        "PostLo": "int",
        "PostHi": "int",
        "RunLo": "int",
        "RunHi": "int",
        "CommTorq": "float",
        "TorqFeed": "float",
        "PowOnTime": "float",
        "ModInd": "float",
        "FluxWeakOut": "float",
        "IdComm": "float",
        "IqComm": "float",
        "ProjCode": "int",
        "SWVer": "int",
        "MMDD": "int",
        "YYYY": "int",
        "DiagRec": "int",
        "DiagSeg": "int",
        "DiagGRes": "float",
        "DiagGObs": "float",
        "DiagSin": "int",
        "FTorqComm": "float",
        "FTorqFeed": "float",
        "FMotRPM": "int",
        "FDCVolt": "float",
        "ParRespAdd": "int",
        "ParRespWri": "int",
        "ParRespDat": "int"
    },
    "drive2_Input": {
        "Time": "str",
        "Unnamed: 1": "float",
        "TorqueComm": "float",
        "SpeedComm": "int",
        "DirectComm": "int",
        "InvEnable": "int",
        "InvDischarge": "int",
        "SpeedModeOn": "int",
        "RollingCount": "int",
        "TorqueLimitComm": "float",
        "ParaAdd": "int",
        "ParaRWComm": "int",
        "ParaData": "int"
    },

    "vehicle": {
        "Time": "str",
        "Unnamed: 1": "float",
        "PLC_HB": "int",
        "24Volt": "int",
        "VCUMode": "int",
        "VehState": "int",
        "WhlSpd": "int",
        "UpTime": "str",
        "DownTime": "str",
        "GearChngeTime": "str",
        "BodyPos": "int",
        "Throttle": "float",
        "BodyUp": "int",
        "BrakeAirPres": "int",
        "BrakeOilTemp": "int",
        "DownShiftOn": "int",
        "HoistPosAve": "int",
        "KeyAccessVolt": "int",
        "Ignition": "int",
        "ParkBrakeLeft": "int",
        "ParkBrakeRight": "int",
        "Retarder": "float",
        "FLStrut": "int",
        "FRStrut": "int",
        "RLStrut": "int",
        "RRStrut": "int",
        "GearReq": "int",
        "GearAct": "int",
        "UpShiftOn": "int",
        "WSpeedLeft": "int",
        "WSpeedRight": "int",
        "PDPPosConClos": "int",
        "PDPNegConClos": "int",
        "PDPChilConClos": "int",
        "PDPDrive1ContClos": "int",
        "PDPDrive2ContClos": "int",
        "PDPAux1ContClos": "int",
        "ChillConn": "int",
        "DriveConn": "int",
        "AuxConn": "int",
        "PDPPosConn": "int",
        "PDPNegConn": "int",
        "PDPDriveConn": "int",
        "PDPAuxConn": "int",
        "PDPChillConn": "int",
        "PDPDcdcConn": "int",
        "PressVal": "float",
        "TempVal": "float",
        "lvVolt": "int",
        "ProcesTemp": "int",
        "PCBTemp": "int",
        "VibVal": "float",
        "G1OutVolt": "int",
        "G2OutVolt": "int",
        "G3GOutVolt": "int",
        "TransDrainOn": "int",
        "BattOn": "int",
        "DcdcOn": "int",
        "DriveOn": "int",
        "AuxOn": "int",
        "Incli_x_raw": "int",
        "Incli_y_raw": "int",
        "Incli_x": "float",
        "Incli_y": "float",
        "CAN0ErrTx": "int",
        "CAN0ErrRx": "int",
        "CAN0BusLoad": "int",
        "CAN0BusState": "int",
        "CAN0MessCount": "int",
        "CAN1ErrTx": "int",
        "CAN1ErrRx": "int",
        "CAN1BusLoad": "int",
        "CAN1BusState": "int",
        "CAN1MessCount": "int",
        "CAN2ErrTx": "int",
        "CAN2ErrRx": "int",
        "CAN2BusLoad": "int",
        "CAN2BusState": "int",
        "CAN2MessCount": "int",
        "CAN3ErrTx": "int",
        "CAN3ErrRx": "int",
        "CAN3BusLoad": "int",
        "CAN3BusState": "int",
        "CAN3MessCount": "int",
        "RPMBefore": "int",
        "RPMAfter": "int",
        "GearChanged": "int",
        "RPMInit": "int",
        "ShutdownSafe": "int",
        "Fault": "float"
    },


    # You can now add: Battery1, Drive1, Drive2, ChargeController1, Vehicle, etc.
}