SCHEMAS = {
    # "auxiliary": {
    #     "Time": "object",
    #     "Unnamed: 1": "float64",
    #     "CanSigActTorq": "int64",
    #     "DCBusCurr": "int64",
    #     "DiIn1": "int64",
    #     "DiIn2": "int64",
    #     "DiIn3": "int64",
    #     "DiIn4": "int64",
    #     "DiIn5": "int64",
    #     "DiIn6": "int64",
    #     "DiIn7": "int64",
    #     "DiIn8": "int64",
    #     "DiIn9": "int64",
    #     "EncIn2A": "int64",
    #     "EncIn2B": "int64",
    #     "DiIn13": "int64",
    #     "EncIn1C": "int64",
    #     "EncIn1A": "int64",
    #     "EncIn1B": "int64",
    #     "AbiAccCurr": "int64",
    #     "IdArms": "int64",
    #     "IqArms": "int64",
    #     "UdRef": "int64",
    #     "UqRef": "int64",
    #     "ActLimType": "int64",
    #     "RegStat": "int64",
    #     "SensAng": "int64",
    #     "Iq": "int64",
    #     "Id": "int64",
    #     "ReaToSWOn": "int64",
    #     "SwOn": "int64",
    #     "Ena": "int64",
    #     "Trip": "float64",
    #     "CurrAbiRed": "float64",
    #     "CurrBoosAct": "float64",
    #     "ErrAct": "float64",
    #     "WarnAct": "float64",
    #     "Regen": "float64",
    #     "ODOut1On": "float64",
    #     "ODOut2On": "float64",
    #     "ODOut3On": "float64",
    #     "ODOut4On": "float64",
    #     "ODOut5On": "float64",
    #     "ODOut6On": "float64",
    #     "CanSigRotSpeedInRPM": "float64",
    #     "CanSigRmsMotCurr": "float64",
    #     "FiltVolt": "float64",
    #     "Event1": "float64",
    #     "Event2": "float64",
    #     "Event3": "float64",
    #     "Event4": "float64",
    #     "MotTemp": "float64",
    #     "HeatSTemp": "float64",
    #     "ActContMode": "float64",
    #     "ActEvent": "float64",
    #     "DCBusPow": "float64",
    #     "UpeakNorm": "float64",
    #     "VoltAng": "float64",
    #     "RefTorq": "float64"
    # },

#     "auxiliary_input": {
#         "Time": "int",
#         "Unnamed: 1": "int",
#         "CommTorq": "int",
#         " CommAcCurr": "int",
#         " CommVolt": "int",
#         " CommControlMode": "int",
#         " CommSwitchOn. CommSpdNeutBrakeRampParSet": "int",
#         " CommEnable": "float",
#         " CommRegulSet": "int",
#         " CommActCurrBoost": "int",
#         " CommSpeedRampParSet": "int",
#         " CommIgnore": "int",
#         "LowDCBus": "int",
#         " CommHighSideSwitchOn": "int",
#         " CommOpenDrain1On": "int",
#         " CommOpenDrain2On": "int",
#         " CommOpenDrain3On": "float",
#         " CommOpenDrain4On": "int",
#         " CommOpenDrain5On": "float",
#         " CommOpenDrain6On": "float",
#         " CommSpeed": "float",
#         " CommAccChang": "int",
#         " CommDecelChange": "int",
#         " AccTorqLimit": "int",
#         " BrakeTorqLimit": "int",
#         " PosDcCurrLimit": "int",
#         " NegDcCurrLimit": "float"
#     },
#     "battery1": {
#         "Time": "int",
#         "Unnamed: 1": "int",
#         "ISOQui": "int",
#         "HWConfFau": "int",
#         "MSDOpen": "int",
#         "DaiCommErr": "int",
#         "DaiCommWarn": "int",
#         "HVILExADC": "int",
#         "HVILInErr": "int",
#         "HVILInADC": "int",
#         "ISOADC": "int",
#         "BDUOPWarn": "int",
#         "BDUOPErr": "int",
#         "InPresVld": "int",
#         "OutPresVld": "int",
#         "CellBalErr": "int",
#         "Aux5VVld": "int",
#         "EnThr": "int",
#         "DisEnThr": "int",
#         "MaxChrPwr": "float",
#         "MaxDisPwr": "float",
#         "CellVMin": "float",
#         "CellVMax": "float",
#         "CoolReq": "int",
#         "HeatReq": "int",
#         "ISOResNeg": "int",
#         "ISOResPos": "int",
#         "SOC": "float",
#         "SOH": "int",
#         "EnRema": "float",
#         "CellSOCMin": "float",
#         "CellSOCMax": "float",
#         "TempAvg": "int",
#         "TempMax": "int",
#         "TempMin": "int",
#         "InPres": "float",
#         "OutPres": "float",
#         "BDUTemp": "int",
#         "BDUHum": "int",
#         "ChrTime": "int",
#         "DisTime": "int",
#         "FullCharCou": "int",
#         "OpTime": "int",
#         "RemChrTime": "int",
#         "MaxChrCurr": "float",
#         "MaxDisCurr": "float",
#         "MaxChrPwrChrgr": "float",
#         "MaxChrCurrChrgr": "float",
#         "LinkVol": "float",
#         "PackCurr": "float",
#         "PackVol": "float",
#         "BattSts": "int",
#         "NegRly": "int",
#         "PosRly": "int",
#         "PreRly": "int",
#         "EndChrSts": "int",
#         "ISOAct": "int",
#         "CAN1": "int",
#         "CAN3": "int",
#         "LED": "int",
#         "PackID": "int",
#         "MaxPackSta": "int",
#         "CAN3Baud": "int",
#         "Heartb": "int",
#         "ConnPackSta": "int",
#         "AccelHi": "int",
#         "CellBal": "int",
#         "MsgLossConf": "int",
#         "HWVer": "int",
#         "SWVer": "int"
#     },
#     "battery1_input": {
#         "Time": "object",
#         "Unnamed: 1": "float",
#         "AmbiTemp": "int",
#         " SetChrgSocLim": "int",
#         " SetChrgVltLim": "int",
#         " SleepCmd": "int",
#         " NormPowUpCmd": "int",
#         " NormPowDownCmd": "int",
#         " EmergPowDownCmd": "int",
#         " PlugInChrgCmd": "int",
#         " EndOfChargeCmd": "int",
#         " ISODisCmd": "int",
#         " DisLEDCmd": "int",
#         " SetDisLedCmd": "int",
#         " SelPackID": "int",
#         " SetPackId": "int",
#         " SelMaxPackInStack": "int",
#         " SetMaxPackInStack": "int",
#         " ConKey": "int",
#         " CrashSts": "int",
#         " ServiceMode": "float",
#         " SetServiceModeCmd": "float"
#     },
#     "chargecontroller1": {
#         "Time": "object",
#         "Unnamed: 1": "float",
#         "PP": "int",
#         "CP": "int",
#         "ACCharPoss": "int",
#         "CPDuty": "int",
#         "InlACTemp": "float",
#         "InlDCTemp": "float",
#         "HVSWTemp": "float",
#         "HVPlugTemp": "float",
#         "AuxTemp": "float",
#         "EVSEID": "int",
#         "PresCurr": "float",
#         "PresVolt": "float",
#         "CRC": "int",
#         "SeqCount": "int",
#         "HVSW1StateReq": "int",
#         "HVSW2StateReq": "int",
#         "PlugState": "int",
#         "IL1State": "int",
#         "IL2State": "int",
#         "EmergShut": "int",
#         "HWVers": "int",
#         "CANVers": "int",
#         "SWMajVers": "int",
#         "SWBuildVers": "int",
#         "SWMinVers": "int",
#         "MinCurrLim": "float",
#         "MinVoltLim": "float",
#         "EnerToBeDeli": "int",
#         "PeakCurrRipp": "float",
#         "CurrRegTol": "float",
#         "EVSEState": "int",
#         "PowLimAch": "int",
#         "CurrLimAch": "int",
#         "VoltLimAch": "int",
#         "WakeUpReas": "int",
#         "LockState": "int",
#         "HVSWState": "int",
#         "CCLState": "int",
#         "TargCurr": "float",
#         "ChargMode": "int",
#         "DTC_AWL": "int",
#         "DTC_PL": "int",
#         "DTC_RSL": "int",
#         "ActChargProt": "int",
#         "MaxCurrLim": "float",
#         "MaxVoltLim": "float",
#         "MaxPowLim": "int",
#         "ErrorNo": "int",
#         "EVSEStatCode": "int",
#         "ButtonState": "int",
#         "ShutDownReq": "int"
#     },
#     "CCL1": {
#         "Time": "object",
#         "Unnamed: 1": "float64",
#         "PP": "int64",
#         "CP": "int64",
#         "ACCharPoss": "int64",
#         "CPDuty": "int64",
#         "InlACTemp": "float64",
#         "InlDCTemp": "float64",
#         "HVSWTemp": "float64",
#         "HVPlugTemp": "float64",
#         "AuxTemp": "float64",
#         "EVSEID": "int64",
#         "PresCurr": "float64",
#         "PresVolt": "float64",
#         "CRC": "int64",
#         "SeqCount": "int64",
#         "HVSW1StateReq": "int64",
#         "HVSW2StateReq": "int64",
#         "PlugState": "int64",
#         "IL1State": "int64",
#         "IL2State": "int64",
#         "EmergShut": "int64",
#         "HWVers": "int64",
#         "CANVers": "int64",
#         "SWMajVers": "int64",
#         "SWBuildVers": "int64",
#         "SWMinVers": "int64",
#         "MinCurrLim": "float64",
#         "MinVoltLim": "float64",
#         "EnerToBeDeli": "int64",
#         "PeakCurrRipp": "float64",
#         "CurrRegTol": "float64",
#         "EVSEState": "int64",
#         "PowLimAch": "int64",
#         "CurrLimAch": "int64",
#         "VoltLimAch": "int64",
#         "WakeUpReas": "int64",
#         "LockState": "int64",
#         "HVSWState": "int64",
#         "CCLState": "int64",
#         "TargCurr": "float64",
#         "ChargMode": "int64",
#         "DTC_AWL": "int64",
#         "DTC_PL": "int64",
#         "DTC_RSL": "int64",
#         "ActChargProt": "int64",
#         "MaxCurrLim": "float64",
#         "MaxVoltLim": "float64",
#         "MaxPowLim": "int64",
#         "ErrorNo": "int64",
#         "EVSEStatCode": "int64",
#         "ButtonState": "int64",
#         "ShutDownReq": "int64"
#     },
#
#     "CCL1_input": {
#         "Time": "object",
#         "Unnamed: 1": "float",
#         "EVCCID": "int",
#         " LED1PWM": "float",
#         " LED2PWM": "float",
#         " LED3PWM": "float",
#         " LED4PWM": "float",
#         " CRC": "int",
#         " SeqCounter": "int",
#         " HVSW1State": "int",
#         " HVSW2State": "int",
#         " VehVolt": "float",
#         " InletVolt": "float",
#         " EmergSep": "int",
#         " EVRemainTimeToBulkSOC": "int",
#         " EVCabinCond": "int",
#         " EVRessCond": "int",
#         " EVBulkSOC": "float",
#         " EVRemTimeToFullSOC": "int",
#         " EVBulkChargComp": "float",
#         " EVFullSOC": "float",
#         " EVTargCurr": "float",
#         " EVTargVolt": "float",
#         " EVSOC": "int",
#         " EVError": "int",
#         " EVEnergReq": "float",
#         " EVDCMaxCurrLimit": "int",
#         " EVDCMaxPowLimit": "float",
#         " EVDCMaxVoltLimit": "int",
#         " LockPerm": "int",
#         " UnlockPerm": "int",
#         " HVReady": "int",
#         " ChargPerm": "int",
#         " RestartChargCyc": "int",
#         " PauseReq": "int",
#         " Reneg": "int"
#     },
#     "chiller1": {
#         "Time": "object",
#         "Unnamed: 1": "float64",
#         "HypStat": "int64",
#         "HypTimeOut": "int64",
#         "DCDCStat": "int64",
#         "DCDCTimeOut": "int64",
#         "WPIntStat": "int64",
#         "WPIntTimeOut": "int64",
#         "WPExtStat": "int64",
#         "WPExtTimeOut": "int64",
#         "HVHStat": "int64",
#         "HVHTimeOut": "int64",
#         "FAN1Stat": "int64",
#         "FAN1TimeOut": "int64",
#         "FAN2Stat": "int64",
#         "FAN2TimeOut": "int64",
#         "HVUndVolt": "int64",
#         "HVOverVolt": "int64",
#         "LVUndVolt": "int64",
#         "LVOverVolt": "int64",
#         "VDD12UndVolt": "int64",
#         "VDD12OverVolt": "int64",
#         "CoolLevStat": "int64",
#         "STCSensStat": "int64",
#         "ECUErr": "int64",
#         "STM": "int64",
#         "DetConfig": "int64",
#         "CoolAvail": "int64",
#         "HeatAvail": "int64",
#         "DetCANProt": "int64",
#         "Fan1Speed": "int64",
#         "Fan2Speed": "int64",
#         "PumpExtSpeed": "int64",
#         "PumpIntSpeed": "int64",
#         "CoolTemp": "int64",
#         "PowConsHVH": "int64",
#         "PowConsHyper": "int64",
#         "PowLimCalc": "int64",
#         "SLIInpPwr": "float64",
#         "HV": "float64",
#         "Cmpr": "int64",
#         "Rel": "float64",
#         "HeatrSts": "int64",
#         "HVILSts": "int64",
#         "Mode": "int64",
#         "CooltLvl": "int64"
#     },
#
#
#     "chiller1_input": {
#         "Time": "object",
#         "Unnamed: 1": "float",
#         " ThermSysStrt": "int",
#         " PackNameThem": "int",
#         " EnaCoolgHeatBat": "int",
#         " TAct": "float",
#         " TSetPoint": "float"
#     },
#
#     "DCDC": {
#         "Time": "float",  # Column is all NaN in df.info()
#         "Unnamed: 1": "int",
#         "CurrOut": "int",
#         "VoltOut": "int",
#         "Temp": "int",
#         "Enabled": "int",
#         "VoltSetpoint": "int",
#         "InputCurr": "int",
#         "InputVolt": "int"
#     },
#     "drive1": {
#         "Time": "object",
#         "Unnamed: 1": "float",
#         "ModATemp": "float",
#         "ModBTemp": "float",
#         "ModCTemp": "float",
#         "GateDriTemp": "float",
#         "ContTemp": "float",
#         "RTD1Temp": "float",
#         "RTD2Temp": "float",
#         "StallBurTemp": "float",
#         "CoolTemp": "float",
#         "HotSpotTemp": "float",
#         "MotTemp": "float",
#         "TorqShud": "float",
#         "OilTemp": "float",
#         "OilPres": "float",
#         "AnIn4": "float",
#         "AnIn5": "float",
#         "AnIn6": "float",
#         "DiIn1": "int",
#         "DiIn2": "int",
#         "DiIn3": "int",
#         "DiIn4": "int",
#         "DiIn5": "int",
#         "DiIn6": "int",
#         "DiIn7": "int",
#         "DiIn8": "int",
#         "MotAngElec": "float",
#         "MotRPM": "int",
#         "ElecOutFreq": "float",
#         "DeltResFilt": "float",
#         "PhaATemp": "float",
#         "PhaBTemp": "float",
#         "PhaCTemp": "float",
#         "DCCurr": "float",
#         "DCVolt": "float",
#         "OutVolt": "float",
#         "VABVd": "float",
#         "VBCVq": "float",
#         "Vdff": "float",
#         "Vqff": "float",
#         "Id": "float",
#         "Iq": "float",
#         "Ref15": "float",
#         "Ref25": "float",
#         "Ref50": "float",
#         "Ref120": "float",
#         "VSM": "int",
#         "PWM": "int",
#         "InvSta": "int",
#         "R1": "int",
#         "R2": "int",
#         "R3": "int",
#         "R4": "int",
#         "R5": "int",
#         "R6": "int",
#         "Run": "int",
#         "SelfSens": "int",
#         "DisSta": "int",
#         "CommMode": "int",
#         "RollCoun": "int",
#         "EnaSta": "int",
#         "BurstMod": "int",
#         "KeySta": "int",
#         "EnaLock": "int",
#         "DirComm": "int",
#         "BMSAct": "int",
#         "BMSTLim": "int",
#         "LimMaxRPM": "int",
#         "LimHotSpot": "int",
#         "LowRPMLim": "int",
#         "LimCoolDer": "int",
#         "LimStallBur": "int",
#         "PostLo": "int",
#         "PostHi": "int",
#         "RunLo": "int",
#         "RunHi": "int",
#         "CommTorq": "float",
#         "TorqFeed": "float",
#         "PowOnTime": "float",
#         "ModInd": "float",
#         "FluxWeakOut": "float",
#         "IdComm": "float",
#         "IqComm": "float",
#         "ProjCode": "int",
#         "SWVer": "int",
#         "MMDD": "int",
#         "YYYY": "int",
#         "DiagRec": "int",
#         "DiagSeg": "int",
#         "DiagGRes": "float",
#         "DiagGObs": "float",
#         "DiagSin": "int",
#         "FTorqComm": "float",
#         "FTorqFeed": "float",
#         "FMotRPM": "int",
#         "FDCVolt": "float",
#         "ParRespAdd": "int",
#         "ParRespWri": "int",
#         "ParRespDat": "int"
#     },
#
#     "drive1_input": {
#         "Time": "object",
#         "Unnamed: 1": "float",
#         "TorqueComm": "float",
#         " SpeedComm": "int",
#         " DirectComm": "int",
#         " InvEnable": "int",
#         " InvDischarge": "int",
#         " SpeedModeOn": "int",
#         " RollingCount": "int",
#         " TorqueLimitComm": "float",
#         " ParaAdd": "int",
#         " ParaRWComm": "int",
#         " ParaData": "int"
#     },
#
#     "drive2": {
#         "Time": "object",
#         "Unnamed: 1": "float",
#         "ModATemp": "float",
#         "ModBTemp": "float",
#         "ModCTemp": "float",
#         "GateDriTemp": "float",
#         "ContTemp": "float",
#         "RTD1Temp": "float",
#         "RTD2Temp": "float",
#         "StallBurTemp": "float",
#         "CoolTemp": "float",
#         "HotSpotTemp": "float",
#         "MotTemp": "float",
#         "TorqShud": "float",
#         "OilTemp": "float",
#         "OilPres": "float",
#         "AnIn4": "float",
#         "AnIn5": "float",
#         "AnIn6": "float",
#         "DiIn1": "int",
#         "DiIn2": "int",
#         "DiIn3": "int",
#         "DiIn4": "int",
#         "DiIn5": "int",
#         "DiIn6": "int",
#         "DiIn7": "int",
#         "DiIn8": "int",
#         "MotAngElec": "float",
#         "MotRPM": "int",
#         "ElecOutFreq": "float",
#         "DeltResFilt": "float",
#         "PhaATemp": "float",
#         "PhaBTemp": "float",
#         "PhaCTemp": "float",
#         "DCCurr": "float",
#         "DCVolt": "float",
#         "OutVolt": "float",
#         "VABVd": "float",
#         "VBCVq": "float",
#         "Vdff": "float",
#         "Vqff": "float",
#         "Id": "float",
#         "Iq": "float",
#         "Ref15": "float",
#         "Ref25": "float",
#         "Ref50": "float",
#         "Ref120": "float",
#         "VSM": "int",
#         "PWM": "int",
#         "InvSta": "int",
#         "R1": "int",
#         "R2": "int",
#         "R3": "int",
#         "R4": "int",
#         "R5": "int",
#         "R6": "int",
#         "Run": "int",
#         "SelfSens": "int",
#         "DisSta": "int",
#         "CommMode": "int",
#         "RollCoun": "int",
#         "EnaSta": "int",
#         "BurstMod": "int",
#         "KeySta": "int",
#         "EnaLock": "int",
#         "DirComm": "int",
#         "BMSAct": "int",
#         "BMSTLim": "int",
#         "LimMaxRPM": "int",
#         "LimHotSpot": "int",
#         "LowRPMLim": "int",
#         "LimCoolDer": "int",
#         "LimStallBur": "int",
#         "PostLo": "int",
#         "PostHi": "int",
#         "RunLo": "int",
#         "RunHi": "int",
#         "CommTorq": "float",
#         "TorqFeed": "float",
#         "PowOnTime": "float",
#         "ModInd": "float",
#         "FluxWeakOut": "float",
#         "IdComm": "float",
#         "IqComm": "float",
#         "ProjCode": "int",
#         "SWVer": "int",
#         "MMDD": "int",
#         "YYYY": "int",
#         "DiagRec": "int",
#         "DiagSeg": "int",
#         "DiagGRes": "float",
#         "DiagGObs": "float",
#         "DiagSin": "int",
#         "FTorqComm": "float",
#         "FTorqFeed": "float",
#         "FMotRPM": "int",
#         "FDCVolt": "float",
#         "ParRespAdd": "int",
#         "ParRespWri": "int",
#         "ParRespDat": "int"
#     },
#     "drive2_Input": {
#         "Time": "str",
#         "Unnamed: 1": "float",
#         "TorqueComm": "float",
#         "SpeedComm": "int",
#         "DirectComm": "int",
#         "InvEnable": "int",
#         "InvDischarge": "int",
#         "SpeedModeOn": "int",
#         "RollingCount": "int",
#         "TorqueLimitComm": "float",
#         "ParaAdd": "int",
#         "ParaRWComm": "int",
#         "ParaData": "int"
#     },
#
#     "vehicle": {
#         "Time": "str",
#         "Unnamed: 1": "float",
#         "PLC_HB": "int",
#         "24Volt": "int",
#         "VCUMode": "int",
#         "VehState": "int",
#         "WhlSpd": "int",
#         "UpTime": "str",
#         "DownTime": "str",
#         "GearChngeTime": "str",
#         "BodyPos": "int",
#         "Throttle": "float",
#         "BodyUp": "int",
#         "BrakeAirPres": "int",
#         "BrakeOilTemp": "int",
#         "DownShiftOn": "int",
#         "HoistPosAve": "int",
#         "KeyAccessVolt": "int",
#         "Ignition": "int",
#         "ParkBrakeLeft": "int",
#         "ParkBrakeRight": "int",
#         "Retarder": "float",
#         "FLStrut": "int",
#         "FRStrut": "int",
#         "RLStrut": "int",
#         "RRStrut": "int",
#         "GearReq": "int",
#         "GearAct": "int",
#         "UpShiftOn": "int",
#         "WSpeedLeft": "int",
#         "WSpeedRight": "int",
#         "PDPPosConClos": "int",
#         "PDPNegConClos": "int",
#         "PDPChilConClos": "int",
#         "PDPDrive1ContClos": "int",
#         "PDPDrive2ContClos": "int",
#         "PDPAux1ContClos": "int",
#         "ChillConn": "int",
#         "DriveConn": "int",
#         "AuxConn": "int",
#         "PDPPosConn": "int",
#         "PDPNegConn": "int",
#         "PDPDriveConn": "int",
#         "PDPAuxConn": "int",
#         "PDPChillConn": "int",
#         "PDPDcdcConn": "int",
#         "PressVal": "float",
#         "TempVal": "float",
#         "lvVolt": "int",
#         "ProcesTemp": "int",
#         "PCBTemp": "int",
#         "VibVal": "float",
#         "G1OutVolt": "int",
#         "G2OutVolt": "int",
#         "G3GOutVolt": "int",
#         "TransDrainOn": "int",
#         "BattOn": "int",
#         "DcdcOn": "int",
#         "DriveOn": "int",
#         "AuxOn": "int",
#         "Incli_x_raw": "int",
#         "Incli_y_raw": "int",
#         "Incli_x": "float",
#         "Incli_y": "float",
#         "CAN0ErrTx": "int",
#         "CAN0ErrRx": "int",
#         "CAN0BusLoad": "int",
#         "CAN0BusState": "int",
#         "CAN0MessCount": "int",
#         "CAN1ErrTx": "int",
#         "CAN1ErrRx": "int",
#         "CAN1BusLoad": "int",
#         "CAN1BusState": "int",
#         "CAN1MessCount": "int",
#         "CAN2ErrTx": "int",
#         "CAN2ErrRx": "int",
#         "CAN2BusLoad": "int",
#         "CAN2BusState": "int",
#         "CAN2MessCount": "int",
#         "CAN3ErrTx": "int",
#         "CAN3ErrRx": "int",
#         "CAN3BusLoad": "int",
#         "CAN3BusState": "int",
#         "CAN3MessCount": "int",
#         "RPMBefore": "int",
#         "RPMAfter": "int",
#         "GearChanged": "int",
#         "RPMInit": "int",
#         "ShutdownSafe": "int",
#         "Fault": "float"
#     }
    "auxiliary": [
        "Time", "Unnamed: 1", "CanSigActTorq", "DCBusCurr", "DiIn1", "DiIn2", "DiIn3",
        "DiIn4", "DiIn5", "DiIn6", "DiIn7", "DiIn8", "DiIn9", "EncIn2A", "EncIn2B",
        "DiIn13", "EncIn1C", "EncIn1A", "EncIn1B", "AbiAccCurr", "IdArms", "IqArms",
        "UdRef", "UqRef", "ActLimType", "RegStat", "SensAng", "Iq", "Id", "ReaToSWOn",
        "SwOn", "Ena", "Trip", "CurrAbiRed", "CurrBoosAct", "ErrAct", "WarnAct", "Regen",
        "ODOut1On", "ODOut2On", "ODOut3On", "ODOut4On", "ODOut5On", "ODOut6On",
        "CanSigRotSpeedInRPM", "CanSigRmsMotCurr", "FiltVolt", "Event1", "Event2",
        "Event3", "Event4", "MotTemp", "HeatSTemp", "ActContMode", "ActEvent", "DCBusPow",
        "UpeakNorm", "VoltAng", "RefTorq"
    ],
    "auxiliary_input": [
        "Time", "Unnamed: 1", "CommTorq", "CommAcCurr", "CommVolt", "CommControlMode",
        "CommSwitchOn. CommSpdNeutBrakeRampParSet", "CommEnable", "CommRegulSet",
        "CommActCurrBoost", "CommSpeedRampParSet", "CommIgnore", "LowDCBus",
        "CommHighSideSwitchOn", "CommOpenDrain1On", "CommOpenDrain2On",
        "CommOpenDrain3On", "CommOpenDrain4On", "CommOpenDrain5On", "CommOpenDrain6On",
        "CommSpeed", "CommAccChang", "CommDecelChange", "AccTorqLimit", "BrakeTorqLimit",
        "PosDcCurrLimit", "NegDcCurrLimit"
    ],
    "battery1": [
        "Time", "Unnamed: 1", "ISOQui", "HWConfFau", "MSDOpen", "DaiCommErr",
        "DaiCommWarn", "HVILExADC", "HVILInErr", "HVILInADC", "ISOADC", "BDUOPWarn",
        "BDUOPErr", "InPresVld", "OutPresVld", "CellBalErr", "Aux5VVld", "EnThr",
        "DisEnThr", "MaxChrPwr", "MaxDisPwr", "CellVMin", "CellVMax", "CoolReq",
        "HeatReq", "ISOResNeg", "ISOResPos", "SOC", "SOH", "EnRema", "CellSOCMin",
        "CellSOCMax", "TempAvg", "TempMax", "TempMin", "InPres", "OutPres", "BDUTemp",
        "BDUHum", "ChrTime", "DisTime", "FullCharCou", "OpTime", "RemChrTime",
        "MaxChrCurr", "MaxDisCurr", "MaxChrPwrChrgr", "MaxChrCurrChrgr", "LinkVol",
        "PackCurr", "PackVol", "BattSts", "NegRly", "PosRly", "PreRly", "EndChrSts",
        "ISOAct", "CAN1", "CAN3", "LED", "PackID", "MaxPackSta", "CAN3Baud", "Heartb",
        "ConnPackSta", "AccelHi", "CellBal", "MsgLossConf", "HWVer", "SWVer"
    ],
    "battery1_input": [
        "Time", "Unnamed: 1", "AmbiTemp", "SetChrgSocLim", "SetChrgVltLim", "SleepCmd",
        "NormPowUpCmd", "NormPowDownCmd", "EmergPowDownCmd", "PlugInChrgCmd",
        "EndOfChargeCmd", "ISODisCmd", "DisLEDCmd", "SetDisLedCmd", "SelPackID",
        "SetPackId", "SelMaxPackInStack", "SetMaxPackInStack", "ConKey", "CrashSts",
        "ServiceMode", "SetServiceModeCmd"
    ],
    "chargecontroller1": [
        "Time", "Unnamed: 1", "PP", "CP", "ACCharPoss", "CPDuty", "InlACTemp",
        "InlDCTemp", "HVSWTemp", "HVPlugTemp", "AuxTemp", "EVSEID", "PresCurr",
        "PresVolt", "CRC", "SeqCount", "HVSW1StateReq", "HVSW2StateReq", "PlugState",
        "IL1State", "IL2State", "EmergShut", "HWVers", "CANVers", "SWMajVers",
        "SWBuildVers", "SWMinVers", "MinCurrLim", "MinVoltLim", "EnerToBeDeli",
        "PeakCurrRipp", "CurrRegTol", "EVSEState", "PowLimAch", "CurrLimAch",
        "VoltLimAch", "WakeUpReas", "LockState", "HVSWState", "CCLState", "TargCurr",
        "ChargMode", "DTC_AWL", "DTC_PL", "DTC_RSL", "ActChargProt", "MaxCurrLim",
        "MaxVoltLim", "MaxPowLim", "ErrorNo", "EVSEStatCode", "ButtonState",
        "ShutDownReq"
    ],
    "CCL1": [
        "Time", "Unnamed: 1", "PP", "CP", "ACCharPoss", "CPDuty", "InlACTemp",
        "InlDCTemp", "HVSWTemp", "HVPlugTemp", "AuxTemp", "EVSEID", "PresCurr",
        "PresVolt", "CRC", "SeqCount", "HVSW1StateReq", "HVSW2StateReq", "PlugState",
        "IL1State", "IL2State", "EmergShut", "HWVers", "CANVers", "SWMajVers",
        "SWBuildVers", "SWMinVers", "MinCurrLim", "MinVoltLim", "EnerToBeDeli",
        "PeakCurrRipp", "CurrRegTol", "EVSEState", "PowLimAch", "CurrLimAch",
        "VoltLimAch", "WakeUpReas", "LockState", "HVSWState", "CCLState", "TargCurr",
        "ChargMode", "DTC_AWL", "DTC_PL", "DTC_RSL", "ActChargProt", "MaxCurrLim",
        "MaxVoltLim", "MaxPowLim", "ErrorNo", "EVSEStatCode", "ButtonState",
        "ShutDownReq"
    ],
    "CCL1_input": [
        "Time", "Unnamed: 1", "EVCCID", "LED1PWM", "LED2PWM", "LED3PWM", "LED4PWM",
        "CRC", "SeqCounter", "HVSW1State", "HVSW2State", "VehVolt", "InletVolt",
        "EmergSep", "EVRemainTimeToBulkSOC", "EVCabinCond", "EVRessCond", "EVBulkSOC",
        "EVRemTimeToFullSOC", "EVBulkChargComp", "EVFullSOC", "EVTargCurr", "EVTargVolt",
        "EVSOC", "EVError", "EVEnergReq", "EVDCMaxCurrLimit", "EVDCMaxPowLimit",
        "EVDCMaxVoltLimit", "LockPerm", "UnlockPerm", "HVReady", "ChargPerm",
        "RestartChargCyc", "PauseReq", "Reneg"
    ],
    "chiller1": [
        "Time", "Unnamed: 1", "HypStat", "HypTimeOut", "DCDCStat", "DCDCTimeOut",
        "WPIntStat", "WPIntTimeOut", "WPExtStat", "WPExtTimeOut", "HVHStat",
        "HVHTimeOut", "FAN1Stat", "FAN1TimeOut", "FAN2Stat", "FAN2TimeOut",
        "HVUndVolt", "HVOverVolt", "LVUndVolt", "LVOverVolt", "VDD12UndVolt",
        "VDD12OverVolt", "CoolLevStat", "STCSensStat", "ECUErr", "STM", "DetConfig",
        "CoolAvail", "HeatAvail", "DetCANProt", "Fan1Speed", "Fan2Speed",
        "PumpExtSpeed", "PumpIntSpeed", "CoolTemp", "PowConsHVH", "PowConsHyper",
        "PowLimCalc", "SLIInpPwr", "HV", "Cmpr", "Rel", "HeatrSts", "HVILSts", "Mode",
        "CooltLvl"
    ],
    "chiller1_input": [
        "Time", "Unnamed: 1", "ThermSysStrt", "PackNameThem", "EnaCoolgHeatBat", "TAct",
        "TSetPoint"
    ],
    "DCDC": [
        "Time", "Unnamed: 1", "CurrOut", "VoltOut", "Temp", "Enabled", "VoltSetpoint",
        "InputCurr", "InputVolt"
    ],

    "drive1": [
        "Time", "Unnamed: 1", "ModATemp", "ModBTemp", "ModCTemp", "GateDriTemp", "ContTemp",
        "RTD1Temp", "RTD2Temp", "StallBurTemp", "CoolTemp", "HotSpotTemp", "MotTemp",
        "TorqShud", "OilTemp", "OilPres", "AnIn4", "AnIn5", "AnIn6", "DiIn1", "DiIn2",
        "DiIn3", "DiIn4", "DiIn5", "DiIn6", "DiIn7", "DiIn8", "MotAngElec", "MotRPM",
        "ElecOutFreq", "DeltResFilt", "PhaATemp", "PhaBTemp", "PhaCTemp", "DCCurr",
        "DCVolt", "OutVolt", "VABVd", "VBCVq", "Vdff", "Vqff", "Id", "Iq", "Ref15",
        "Ref25", "Ref50", "Ref120", "VSM", "PWM", "InvSta", "R1", "R2", "R3", "R4", "R5",
        "R6", "Run", "SelfSens", "DisSta", "CommMode", "RollCoun", "EnaSta", "BurstMod",
        "KeySta", "EnaLock", "DirComm", "BMSAct", "BMSTLim", "LimMaxRPM", "LimHotSpot",
        "LowRPMLim", "LimCoolDer", "LimStallBur", "PostLo", "PostHi", "RunLo", "RunHi",
        "CommTorq", "TorqFeed", "PowOnTime", "ModInd", "FluxWeakOut", "IdComm", "IqComm",
        "ProjCode", "SWVer", "MMDD", "YYYY", "DiagRec", "DiagSeg", "DiagGRes", "DiagGObs",
        "DiagSin", "FTorqComm", "FTorqFeed", "FMotRPM", "FDCVolt", "ParRespAdd",
        "ParRespWri", "ParRespDat"
    ],
    "drive1_input": [
        "Time", "Unnamed: 1", "TorqueComm", "SpeedComm", "DirectComm", "InvEnable",
        "InvDischarge", "SpeedModeOn", "RollingCount", "TorqueLimitComm", "ParaAdd",
        "ParaRWComm", "ParaData"
    ],
    "drive2": [
        "Time", "Unnamed: 1", "ModATemp", "ModBTemp", "ModCTemp", "GateDriTemp", "ContTemp",
        "RTD1Temp", "RTD2Temp", "StallBurTemp", "CoolTemp", "HotSpotTemp", "MotTemp",
        "TorqShud", "OilTemp", "OilPres", "AnIn4", "AnIn5", "AnIn6", "DiIn1", "DiIn2",
        "DiIn3", "DiIn4", "DiIn5", "DiIn6", "DiIn7", "DiIn8", "MotAngElec", "MotRPM",
        "ElecOutFreq", "DeltResFilt", "PhaATemp", "PhaBTemp", "PhaCTemp", "DCCurr",
        "DCVolt", "OutVolt", "VABVd", "VBCVq", "Vdff", "Vqff", "Id", "Iq", "Ref15",
        "Ref25", "Ref50", "Ref120", "VSM", "PWM", "InvSta", "R1", "R2", "R3", "R4", "R5",
        "R6", "Run", "SelfSens", "DisSta", "CommMode", "RollCoun", "EnaSta", "BurstMod",
        "KeySta", "EnaLock", "DirComm", "BMSAct", "BMSTLim", "LimMaxRPM", "LimHotSpot",
        "LowRPMLim", "LimCoolDer", "LimStallBur", "PostLo", "PostHi", "RunLo", "RunHi",
        "CommTorq", "TorqFeed", "PowOnTime", "ModInd", "FluxWeakOut", "IdComm", "IqComm",
        "ProjCode", "SWVer", "MMDD", "YYYY", "DiagRec", "DiagSeg", "DiagGRes", "DiagGObs",
        "DiagSin", "FTorqComm", "FTorqFeed", "FMotRPM", "FDCVolt", "ParRespAdd",
        "ParRespWri", "ParRespDat"
    ],
    "drive2_Input": [
        "Time", "Unnamed: 1", "TorqueComm", "SpeedComm", "DirectComm", "InvEnable",
        "InvDischarge", "SpeedModeOn", "RollingCount", "TorqueLimitComm", "ParaAdd",
        "ParaRWComm", "ParaData"
    ],
    "vehicle": [
        "Time", "Unnamed: 1", "PLC_HB", "24Volt", "VCUMode", "VehState", "WhlSpd",
        "UpTime", "DownTime", "GearChngeTime", "BodyPos", "Throttle", "BodyUp",
        "BrakeAirPres", "BrakeOilTemp", "DownShiftOn", "HoistPosAve", "KeyAccessVolt",
        "Ignition", "ParkBrakeLeft", "ParkBrakeRight", "Retarder", "FLStrut", "FRStrut",
        "RLStrut", "RRStrut", "GearReq", "GearAct", "UpShiftOn", "WSpeedLeft",
        "WSpeedRight", "PDPPosConClos", "PDPNegConClos", "PDPChilConClos",
        "PDPDrive1ContClos", "PDPDrive2ContClos", "PDPAux1ContClos", "ChillConn",
        "DriveConn", "AuxConn", "PDPPosConn", "PDPNegConn", "PDPDriveConn",
        "PDPAuxConn", "PDPChillConn", "PDPDcdcConn", "PressVal", "TempVal", "lvVolt",
        "ProcesTemp", "PCBTemp", "VibVal", "G1OutVolt", "G2OutVolt", "G3GOutVolt",
        "TransDrainOn", "BattOn", "DcdcOn", "DriveOn", "AuxOn", "Incli_x_raw",
        "Incli_y_raw", "Incli_x", "Incli_y", "CAN0ErrTx", "CAN0ErrRx", "CAN0BusLoad",
        "CAN0BusState", "CAN0MessCount", "CAN1ErrTx", "CAN1ErrRx", "CAN1BusLoad",
        "CAN1BusState", "CAN1MessCount", "CAN2ErrTx", "CAN2ErrRx", "CAN2BusLoad",
        "CAN2BusState", "CAN2MessCount", "CAN3ErrTx", "CAN3ErrRx", "CAN3BusLoad",
        "CAN3BusState", "CAN3MessCount", "RPMBefore", "RPMAfter", "GearChanged",
        "RPMInit", "ShutdownSafe", "Fault"
    ],
    # You can now add: Battery1, Drive1, Drive2, ChargeController1, Vehicle, etc.
    "auxiliary_processed" : {"datetime": "datetime64[ns]",
"cansigacttorq": "float64",
"dcbuscurr": "int64",
"diin1": "int64",
"diin2": "int64",
"diin3": "int64",
"diin4": "int64",
"diin5": "int64",
"diin6": "int64",
"diin7": "int64",
"diin8": "int64",
"diin9": "int64",
"encin2a": "int64",
"encin2b": "int64",
"diin13": "int64",
"encin1c": "int64",
"encin1a": "int64",
"encin1b": "int64",
"abiacccurr": "int64",
"idarms": "float64",
"iqarms": "float64",
"udref": "int64",
"uqref": "int64",
"actlimtype": "int64",
"regstat": "int64",
"sensang": "float64",
"iq": "int64",
"id": "int64",
"reatoswon": "int64",
"swon": "int64",
"ena": "int64",
"trip": "float64",
"currabired": "float64",
"currboosact": "float64",
"erract": "float64",
"warnact": "float64",
"regen": "float64",
"odout1on": "float64",
"odout2on": "float64",
"odout3on": "float64",
"odout4on": "float64",
"odout5on": "float64",
"odout6on": "float64",
"cansigrotspeedinrpm": "float64",
"cansigrmsmotcurr": "float64",
"filtvolt": "float64",
"event1": "float64",
"event2": "float64",
"event3": "float64",
"event4": "float64",
"mottemp": "float64",
"heatstemp": "float64",
"actcontmode": "float64",
"actevent": "float64",
"dcbuspow": "float64",
"upeaknorm": "float64",
"voltang": "float64",
"reftorq": "float64"
},
    "battery1_processed" : {"datetime": "datetime64[ns]",
"isoqui": "int64",
"hwconffau": "int64",
"msdopen": "int64",
"daicommerr": "int64",
"daicommwarn": "int64",
"hvilexadc": "int64",
"hvilinerr": "int64",
"hvilinadc": "int64",
"isoadc": "int64",
"bduopwarn": "int64",
"bduoperr": "int64",
"inpresvld": "int64",
"outpresvld": "int64",
"cellbalerr": "int64",
"aux5vvld": "int64",
"enthr": "int64",
"disenthr": "int64",
"maxchrpwr": "float64",
"maxdispwr": "float64",
"cellvmin": "float64",
"cellvmax": "float64",
"coolreq": "int64",
"heatreq": "int64",
"isoresneg": "int64",
"isorespos": "int64",
"soc": "float64",
"soh": "int64",
"enrema": "float64",
"cellsocmin": "float64",
"cellsocmax": "float64",
"tempavg": "int64",
"tempmax": "int64",
"tempmin": "int64",
"inpres": "float64",
"outpres": "float64",
"bdutemp": "int64",
"bduhum": "int64",
"chrtime": "int64",
"distime": "int64",
"fullcharcou": "int64",
"optime": "int64",
"remchrtime": "int64",
"maxchrcurr": "float64",
"maxdiscurr": "float64",
"maxchrpwrchrgr": "float64",
"maxchrcurrchrgr": "float64",
"linkvol": "float64",
"packcurr": "float64",
"packvol": "float64",
"battsts": "int64",
"negrly": "int64",
"posrly": "int64",
"prerly": "int64",
"endchrsts": "int64",
"isoact": "int64",
"can1": "int64",
"can3": "int64",
"led": "int64",
"packid": "int64",
"maxpacksta": "int64",
"can3baud": "int64",
"heartb": "int64",
"connpacksta": "int64",
"accelhi": "int64",
"cellbal": "int64",
"msglossconf": "int64",
"hwver": "int64",
"swver": "int64"
},
    "ccl1_processed" : {"datetime": "datetime64[ns]",
"pp": "int64",
"cp": "int64",
"accharposs": "int64",
"cpduty": "int64",
"inlactemp": "float64",
"inldctemp": "float64",
"hvswtemp": "float64",
"hvplugtemp": "float64",
"auxtemp": "float64",
"evseid": "int64",
"prescurr": "float64",
"presvolt": "float64",
"crc": "int64",
"seqcount": "int64",
"hvsw1statereq": "int64",
"hvsw2statereq": "int64",
"plugstate": "int64",
"il1state": "int64",
"il2state": "int64",
"emergshut": "int64",
"hwvers": "int64",
"canvers": "int64",
"swmajvers": "int64",
"swbuildvers": "int64",
"swminvers": "int64",
"mincurrlim": "float64",
"minvoltlim": "float64",
"enertobedeli": "int64",
"peakcurrripp": "float64",
"currregtol": "float64",
"evsestate": "int64",
"powlimach": "int64",
"currlimach": "int64",
"voltlimach": "int64",
"wakeupreas": "int64",
"lockstate": "int64",
"hvswstate": "int64",
"cclstate": "int64",
"targcurr": "float64",
"chargmode": "int64",
"dtc_awl": "int64",
"dtc_pl": "int64",
"dtc_rsl": "int64",
"actchargprot": "int64",
"maxcurrlim": "float64",
"maxvoltlim": "float64",
"maxpowlim": "int64",
"errorno": "int64",
"evsestatcode": "int64",
"buttonstate": "int64",
"shutdownreq": "int64"
},
    "chargercontroller1_processed": {"datetime": "datetime64[ns]",
"pp": "int64",
"cp": "int64",
"accharposs": "int64",
"cpduty": "int64",
"inlactemp": "float64",
"inldctemp": "float64",
"hvswtemp": "float64",
"hvplugtemp": "float64",
"auxtemp": "float64",
"evseid": "int64",
"prescurr": "float64",
"presvolt": "float64",
"crc": "int64",
"seqcount": "int64",
"hvsw1statereq": "int64",
"hvsw2statereq": "int64",
"plugstate": "int64",
"il1state": "int64",
"il2state": "int64",
"emergshut": "int64",
"hwvers": "int64",
"canvers": "int64",
"swmajvers": "int64",
"swbuildvers": "int64",
"swminvers": "int64",
"mincurrlim": "float64",
"minvoltlim": "float64",
"enertobedeli": "int64",
"peakcurrripp": "float64",
"currregtol": "float64",
"evsestate": "int64",
"powlimach": "int64",
"currlimach": "int64",
"voltlimach": "int64",
"wakeupreas": "int64",
"lockstate": "int64",
"hvswstate": "int64",
"cclstate": "int64",
"targcurr": "float64",
"chargmode": "int64",
"dtc_awl": "int64",
"dtc_pl": "int64",
"dtc_rsl": "int64",
"actchargprot": "int64",
"maxcurrlim": "float64",
"maxvoltlim": "float64",
"maxpowlim": "int64",
"errorno": "int64",
"evsestatcode": "int64",
"buttonstate": "int64",
"shutdownreq": "int64"
},
    "chiller1_processed": {
"datetime": "datetime64[ns]",
"hypstat": "int64",
"hyptimeout": "int64",
"dcdcstat": "int64",
"dcdctimeout": "int64",
"wpintstat": "int64",
"wpinttimeout": "int64",
"wpextstat": "int64",
"wpexttimeout": "int64",
"hvhstat": "int64",
"hvhtimeout": "int64",
"fan1stat": "int64",
"fan1timeout": "int64",
"fan2stat": "int64",
"fan2timeout": "int64",
"hvundvolt": "int64",
"hvovervolt": "int64",
"lvundvolt": "int64",
"lvovervolt": "int64",
"vdd12undvolt": "int64",
"vdd12overvolt": "int64",
"coollevstat": "int64",
"stcsensstat": "int64",
"ecuerr": "int64",
"stm": "int64",
"detconfig": "int64",
"coolavail": "int64",
"heatavail": "int64",
"detcanprot": "int64",
"fan1speed": "int64",
"fan2speed": "int64",
"pumpextspeed": "int64",
"pumpintspeed": "int64",
"cooltemp": "int64",
"powconshvh": "int64",
"powconshyper": "int64",
"powlimcalc": "int64",
"sliinppwr": "float64",
"hv": "float64",
"cmpr": "int64",
"rel": "float64",
"heatrsts": "int64",
"hvilsts": "int64",
"mode": "int64",
"cooltlvl": "int64"
    },
    "dcdc1_processed": {"datetime": "datetime64[ns]",
"currout": "int64",
"voltout": "int64",
"temp": "int64",
"enabled": "int64",
"voltsetpoint": "int64",
"inputcurr": "int64",
"inputvolt": "int64"
},
    "drive1_processed": {"datetime": "datetime64[ns]",
"modatemp": "float64",
"modbtemp": "float64",
"modctemp": "float64",
"gatedritemp": "float64",
"conttemp": "float64",
"rtd1temp": "float64",
"rtd2temp": "float64",
"stallburtemp": "float64",
"cooltemp": "float64",
"hotspottemp": "float64",
"mottemp": "float64",
"torqshud": "float64",
"oiltemp": "float64",
"oilpres": "float64",
"anin4": "float64",
"anin5": "float64",
"anin6": "float64",
"diin1": "int64",
"diin2": "int64",
"diin3": "int64",
"diin4": "int64",
"diin5": "int64",
"diin6": "int64",
"diin7": "int64",
"diin8": "int64",
"motangelec": "float64",
"motrpm": "int64",
"elecoutfreq": "float64",
"deltresfilt": "float64",
"phaatemp": "float64",
"phabtemp": "float64",
"phactemp": "float64",
"dccurr": "float64",
"dcvolt": "float64",
"outvolt": "float64",
"vabvd": "float64",
"vbcvq": "float64",
"vdff": "float64",
"vqff": "float64",
"id": "float64",
"iq": "float64",
"ref15": "float64",
"ref25": "float64",
"ref50": "float64",
"ref120": "float64",
"vsm": "int64",
"pwm": "int64",
"invsta": "int64",
"r1": "int64",
"r2": "int64",
"r3": "int64",
"r4": "int64",
"r5": "int64",
"r6": "int64",
"run": "int64",
"selfsens": "int64",
"dissta": "int64",
"commmode": "int64",
"rollcoun": "int64",
"enasta": "int64",
"burstmod": "int64",
"keysta": "int64",
"enalock": "int64",
"dircomm": "int64",
"bmsact": "int64",
"bmstlim": "int64",
"limmaxrpm": "int64",
"limhotspot": "int64",
"lowrpmlim": "int64",
"limcoolder": "int64",
"limstallbur": "int64",
"postlo": "int64",
"posthi": "int64",
"runlo": "int64",
"runhi": "int64",
"commtorq": "float64",
"torqfeed": "float64",
"powontime": "float64",
"modind": "float64",
"fluxweakout": "float64",
"idcomm": "float64",
"iqcomm": "float64",
"projcode": "int64",
"swver": "int64",
"mmdd": "int64",
"yyyy": "int64",
"diagrec": "int64",
"diagseg": "int64",
"diaggres": "float64",
"diaggobs": "float64",
"diagsin": "int64",
"ftorqcomm": "float64",
"ftorqfeed": "float64",
"fmotrpm": "int64",
"fdcvolt": "float64",
"parrespadd": "int64",
"parrespwri": "int64",
"parrespdat": "int64"
},
    "drive2_processed": {"datetime": "datetime64[ns]",
"torquecomm": "float64",
"speedcomm": "int64",
"directcomm": "int64",
"invenable": "int64",
"invdischarge": "int64",
"speedmodeon": "int64",
"rollingcount": "int64",
"torquelimitcomm": "float64",
"paraadd": "int64",
"pararwcomm": "int64",
"paradata": "int64"
},
    "vehicle_processed":{
        "datetime": "datetime64[ns]",
        "plc_hb": "int64",
        "24volt": "int64",
        "vcumode": "int64",
        "vehstate": "int64",
        "whlspd": "int64",
        "uptime": "object",
        "downtime": "object",
        "gearchngetime": "object",
        "bodypos": "int64",
        "throttle": "float64",
        "bodyup": "int64",
        "brakeairpres": "int64",
        "brakeoiltemp": "int64",
        "downshifton": "int64",
        "hoistposave": "int64",
        "keyaccessvolt": "int64",
        "ignition": "int64",
        "parkbrakeleft": "int64",
        "parkbrakeright": "int64",
        "retarder": "float64",
        "flstrut": "int64",
        "frstrut": "int64",
        "rlstrut": "int64",
        "rrstrut": "int64",
        "gearreq": "int64",
        "gearact": "int64",
        "upshifton": "int64",
        "wspeedleft": "int64",
        "wspeedright": "int64",
        "pdpposconclos": "int64",
        "pdpnegconclos": "int64",
        "pdpchilconclos": "int64",
        "pdpdrive1contclos": "int64",
        "pdpdrive2contclos": "int64",
        "pdpaux1contclos": "int64",
        "chillconn": "int64",
        "driveconn": "int64",
        "auxconn": "int64",
        "pdpposconn": "int64",
        "pdpnegconn": "int64",
        "pdpdriveconn": "int64",
        "pdpauxconn": "int64",
        "pdpchillconn": "int64",
        "pdpdcdcconn": "int64",
        "pressval": "float64",
        "tempval": "float64",
        "lvvolt": "int64",
        "procestemp": "int64",
        "pcbtemp": "int64",
        "vibval": "float64",
        "g1outvolt": "int64",
        "g2outvolt": "int64",
        "g3goutvolt": "int64",
        "transdrainon": "int64",
        "batton": "int64",
        "dcdcon": "int64",
        "driveon": "int64",
        "auxon": "int64",
        "incli_x_raw": "int64",
        "incli_y_raw": "int64",
        "incli_x": "float64",
        "incli_y": "float64",
        "can0errtx": "int64",
        "can0errrx": "int64",
        "can0busload": "int64",
        "can0busstate": "int64",
        "can0messcount": "int64",
        "can1errtx": "int64",
        "can1errrx": "int64",
        "can1busload": "int64",
        "can1busstate": "int64",
        "can1messcount": "int64",
        "can2errtx": "int64",
        "can2errrx": "int64",
        "can2busload": "int64",
        "can2busstate": "int64",
        "can2messcount": "int64",
        "can3errtx": "int64",
        "can3errrx": "int64",
        "can3busload": "int64",
        "can3busstate": "int64",
        "can3messcount": "int64",
        "rpmbefore": "int64",
        "rpmafter": "int64",
        "gearchanged": "int64",
        "rpminit": "int64",
        "shutdownsafe": "int64"
    }

}